package awsrulesfn

// aws-sdk-go-v2 does not export partition metadata, so copy the files from vendor to make it accessible.
//go:generate bash -c "echo '// Code generated by go generate; DO NOT EDIT.' > partition.go && cat $(go list -m -f '{{.Dir}}' github.com/aws/aws-sdk-go-v2)/internal/endpoints/awsrulesfn/partition.go >> partition.go"
//go:generate bash -c "echo '// Code generated by go generate; DO NOT EDIT.' > partitions.go && cat $(go list -m -f '{{.Dir}}' github.com/aws/aws-sdk-go-v2)/internal/endpoints/awsrulesfn/partitions.go >> partitions.go"
